apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: depsvcresources.customcontroller.k8s.io
spec:
  group: customcontroller.k8s.io
  version: v1alpha1
  names:
    kind: DepSvcResource
    plural: depsvcresources
  scope: Namespaced
